name: CraigStantonWeb
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  flutter_rounded_progress_bar: null
  flutter_email_sender: ^2.2.1
  google_fonts: ^1.1.0
  flutter_form_builder: ^3.14.0-alpha.1
  # below is needed to fix bug with flutter web and flutter form builder - may remove in the future
  # described in this issue thread https://github.com/flutter/flutter/issues/57275
  flutter_chips_input: ^1.9.0-dev.1
  # below only needed because upload currently not supported for web in flutter_form_builder
  # this was the package that should work but it doesnt
  # form_builder_file_picker: ^0.2.0
  file_picker_cross: ^3.0.2
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  provider: ^4.3.2
  flutter_auth_buttons: ^0.9.0
  firebase_web: ^5.0.9
  carousel_slider: ^2.2.1
  platform_info: ^1.1.1+3
  flutter_markdown: ^0.4.3
  flare_flutter: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - animations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: menu
      fonts:
        - asset: fonts/f_menu.ttf
    - family: heading
      fonts:
        - asset: fonts/f_heading.ttf
    - family: content
      fonts:
        - asset: fonts/f_content.ttf
    - family: Special Elite
      fonts:
        - asset: fonts/SpecialElite-Regular.ttf
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-VariableFont_wght.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
